// Cross-validation logic over the reference baselines (EU = Eurostat in
// baseline.js; US = EIA in baseline-us.js). Hand-written; the data files are
// generated by scripts/refresh-baseline*.mjs. Loaded after both data files.
window.OET = window.OET || {};

(function () {
  // Reference price for a country as USD/kWh (nominal).
  OET.baselineUsd = function (cc) {
    if (cc === 'US') return (OET.BASELINE_US && OET.BASELINE_US.national) || null;
    const b = OET.BASELINE && OET.BASELINE[cc];
    if (!b) return null;
    const eurUsd = (OET.FX && OET.FX.EUR) || 1.1;
    return b.eur * eurUsd;
  };

  function medianUsd(ps) {
    const us = ps.map((r) => OET.toUsd(r.rate, r.meta.currency)).filter((v) => v > 0).sort((a, b) => a - b);
    return us.length ? us[us.length >> 1] : null;
  }
  function verdict(ref, med) {
    if (med == null) return { ref, ours: null, status: 'no-data' };
    const ratio = med / ref;
    return { ref, ours: med, ratio, status: ratio >= 0.75 && ratio <= 1.34 ? 'match' : 'diverge' };
  }

  // Cross-check our community median for a country vs its reference. ±25% = match
  // (externally corroborated -> Beta-eligible); outside = diverge; no ref = null.
  OET.crossCheck = function (cc) {
    const ref = OET.baselineUsd(cc);
    if (ref == null) return null;
    return verdict(ref, medianUsd((OET.PLANS || []).filter((r) => r.meta.country === cc)));
  };

  // Per-US-state cross-check (EIA), for the plan modal. null if no state reference.
  OET.crossCheckRegion = function (cc, region) {
    if (cc !== 'US' || !region || !OET.BASELINE_US || !OET.BASELINE_US.states) return null;
    const ref = OET.BASELINE_US.states[region];
    if (ref == null) return null;
    return verdict(ref, medianUsd((OET.PLANS || []).filter((r) => r.meta.country === 'US' && r.meta.region === region)));
  };
})();
